//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCategory
    {
        public int MOVIE_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
