//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInfo
    {
        public int Id { get; set; }
        public string Ref_Id { get; set; }
        public string Payment_Status { get; set; }
        public Nullable<bool> Is_Void { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public Nullable<int> Check_Number { get; set; }
        public Nullable<int> Credit_Card_Type_Id { get; set; }
        public int Payment_Id { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
