//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInfo
    {
        public int ID { get; set; }
        public string REF_ID { get; set; }
        public string PAYMENT_STATUS { get; set; }
        public Nullable<bool> IS_VOID { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
        public Nullable<int> CHECK_NUMBER { get; set; }
        public Nullable<int> CREDIT_CARD_TYPE_ID { get; set; }
        public int PAYMENT_ID { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
