//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentInfoes = new HashSet<PaymentInfo>();
        }
    
        public int Id { get; set; }
        public int Payment_Type_Id { get; set; }
        public decimal Amount_Due { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public bool Is_Paid { get; set; }
        public int Rental_Id { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Rental Rental { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
    }
}
