//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int ID { get; set; }
        public int PERSON_ID { get; set; }
        public int PHONE_TYPE_ID { get; set; }
        public string NUMBER { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
